# For more info on HTTP files go to https://aka.ms/vs/httpfile

@environment kubernetes

# Health
GET {{HostAddress}}/health

###


# Accept the new order
@OrderId=4568968c-dfe6-4221-a14b-74205e5f4ddb
PUT {{HostAddress}}/api/orders/{{OrderId}}/accept

###
